# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

  AppBundle\DataFixtures\:
    resource: '../../src/AppBundle/DataFixtures'
    tags: ['doctrine.fixture.orm']

  security.access.task_voter:
    class: AppBundle\Security\TaskVoter
    public:     false
    tags:
      - { name: security.voter }
    arguments:
      ['@security.access.decision_manager']

  AppBundle\Command\TaskAuditCommand:
    tags:
      - { name: 'taskaudit.command', command: 'task:audit' }

  service.task_manager:
    class: AppBundle\Service\TaskManager
    public:     true
    tags:
      - { name: service.task_manager }
    arguments:
      ['@doctrine.orm.default_entity_manager', '@service_container']

  service.user_manager:
    class: AppBundle\Service\UserManager
    public:     true
    tags:
      - { name: service.user_manager }
    arguments:
      ['@doctrine.orm.default_entity_manager', '@?']

  app.security.access_denied_handler:
    class: AppBundle\Security\AccessDeniedHandler
    autowire: true